### ISSUE TITLE
UnwrapError is not pickleable

### ISSUE THREAD

**Issue by indigoviolet** [rustedpy/result#200]
```python
In [38]: pickle.loads(pickle.dumps(UnwrapError(Err(None), 'foo')))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[38], line 1
----> 1 pickle.loads(pickle.dumps(UnwrapError(Err(None), 'foo')))

TypeError: UnwrapError.__init__() missing 1 required positional argument: 'message'

```
The reason this matters is that sometimes you want exceptions to come back over process boundaries, for ex. while using `multiprocessing`.

**Comment by bygl1** [comment]
Actual error in `extract_combined` for context:

```
2024-12-03 16:51:53.368 | INFO     | pdf_anonymizer.utils.concurrent:map_with_progress:258 - Executing len(inputs)=1 inputs with ProcessPoolExecutor | trace=projects/local/traces/47bc02350bad4b6b0245062aea40bfb0 | sampled=True | span_id=5128e24e29a48b55 | image_tag=
bashed-ahead-post__c35590e3/abashed-ahead-post__c35590e3.pdf: 100%|██████████████████████████████████| 1/1 [00:08<00:00,  8.57s/it, failed=0]
concurrent.futures.process._RemoteTraceback:                                                                                                 
'''
Traceback (most recent call last):
  File "/Users/george/.rye/py/cpython@3.11.9/lib/python3.11/concurrent/futures/process.py", line 424, in wait_result_broken_or_wakeup
    result_item = result_reader.recv()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/.rye/py/cpython@3.11.9/lib/python3.11/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UnwrapError.__init__() missing 1 required positional argument: 'message'
'''
```

**Comment by wbolster** [comment]
thanks for your interest, but this project is no longer maintained (see https://github.com/rustedpy/result/issues/201), and this issue or pull request was closed prior to archiving the repository.
